<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.toolisticon.maven.parent</groupId>
    <artifactId>maven-parent-kotlin-base</artifactId>
    <version>2025.10.2</version>
    <relativePath/>
  </parent>

  <name>Holi-Bank Fixtures - Root</name>
  <description>A working CQRS/ES application used as test fixtures for further lib development.</description>
  <url>https://github.com/holixon/holi-bank-fixtures/</url>

  <groupId>io.holixon.fixtures.holibank</groupId>
  <artifactId>holi-bank-fixtures-root</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
<!--    <module>fixtures</module>-->
    <!-- See below. Examples is included via profile -->
  </modules>

  <properties>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>

    <spring-boot.version>4.0.1</spring-boot.version>
    <axon-bom.version>4.12.1</axon-bom.version>
    <avro.version>1.12.0</avro.version>

    <junit5.version>5.7.2</junit5.version>
    <jgiven.version>2.0.2</jgiven.version>
    <dom4j.version>2.1.3</dom4j.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
<!--      <dependency>-->
<!--        <groupId>org.axonframework</groupId>-->
<!--        <artifactId>axon-bom</artifactId>-->
<!--        <version>${axon-bom.version}</version>-->
<!--        <type>pom</type>-->
<!--        <scope>import</scope>-->
<!--      </dependency>-->
    </dependencies>
  </dependencyManagement>

  <build>

    <!--
      Default build
    -->
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <!-- deploy and release configuration -->
  <distributionManagement>
    <site>
      <id>README</id>
      <url>https://github.com/holixon/holi-bank-fixtures</url>
    </site>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <uniqueVersion>true</uniqueVersion>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
      <uniqueVersion>false</uniqueVersion>
    </repository>
  </distributionManagement>

  <scm>
    <connection>scm:git:git://github.com/holixon/holi-bank-fixtures.git</connection>
    <developerConnection>scm:git:git@github.com:holixon/holi-bank-fixtures.git</developerConnection>
    <url>https://github.com/holixon/holi-bank-fixtures</url>
    <tag>HEAD</tag>
  </scm>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/holixon/holi-bank-fixtures/issues</url>
  </issueManagement>

  <developers>
    <developer>
      <name>Jan Galinski</name>
      <email>jan.galinski@holisticon.de</email>
      <organization>Holisticon AG</organization>
      <organizationUrl>https://holisticon.de</organizationUrl>
      <roles>
        <role>Developer</role>
      </roles>
    </developer>
    <developer>
      <name>Simon Zambrovski</name>
      <email>simon.zambrovski@holisticon.de</email>
      <organization>Holisticon AG</organization>
      <organizationUrl>https://holisticon.de</organizationUrl>
      <roles>
        <role>Developer</role>
      </roles>
    </developer>
  </developers>

  <!-- License Stuff -->
  <inceptionYear>2021</inceptionYear>
  <licenses>
    <license>
      <name>Apache 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <organization>
    <name>Holisticon AG</name>
    <url>https://holisticon.de</url>
  </organization>
</project>
