server:
  port: 9091

spring:
  application:
    name: holi-bank-jpa
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


axon:
  aggregate:
    bank-account:
      snapshot-threshold: 5
  axonserver:
    enabled: false
  serializer:
    general: xstream

springdoc:
  swagger-ui:
    path: "/swagger-ui/index.html"
    use-root-path: true


logging:
  level:
    org.springframework.context.support: WARN

