server:
  port: 9090

spring:
  application:
    name: holi-bank

axon:
  aggregate:
    bank-account:
      snapshot-threshold: 5
  axonserver:
    enabled: true
  serializer:
    general: xstream

springdoc:
  swagger-ui:
    path: "/swagger-ui/index.html"
    use-root-path: true


logging:
  level:
    org.springframework.context.support: WARN

